### ISSUE TITLE
REPORTE ENTREVISTA

### ISSUE THREAD

**Issue by Kim-Mendoza3** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-jka#1]
https://drive.google.com/file/d/1rDPnvOhb8r3dKuEAOlx8X79Ta3l_jgiM/view?usp=sharing

**Comment by Luisangelriverosbautista** [comment]
20 ME PARECE QUE CUMPLE BIEN

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
